name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t karsa007/my-node-app:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push karsa007/my-node-app:latest

    # Deploy Docker image to EC2 Docker server
    - name: SSH and deploy Docker image to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull karsa007/my-node-app:latest
          docker stop karsa007/my-node-app || true
          docker rm karsa007/my-node-app || true
          docker run -d -p 4001:4001 --name my-node-app karsa007/my-node-app:latest
